### ISSUE TITLE
gcc 4.4/CentOS 6 support dropped in master's tip

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#407]
Hello,
I am trying to compile the tip of master and the build failes on gcc4.4/CentOS 6. Did you drop support for CentOS 6 on purpose?

These are the errors I am getting.

```
/workspace/build/cgru-master/afanasy/src/libafanasy/name_affile.cpp: In function ‘const std::string af::pathUp(const std::string&, bool)’:
/workspace/build/cgru-master/afanasy/src/libafanasy/name_affile.cpp:111: error: ‘struct std::string’ has no member named ‘back’
/workspace/build/cgru-master/afanasy/src/libafanasy/name_affile.cpp:112: error: ‘struct std::string’ has no member named ‘pop_back’
/workspace/build/cgru-master/afanasy/src/libafanasy/name_affile.cpp:113: error: ‘struct std::string’ has no member named ‘back’
/workspace/build/cgru-master/afanasy/src/libafanasy/name_affile.cpp:114: error: ‘struct std::string’ has no member named ‘pop_back’



/workspace/build/cgru-master/afanasy/src/libafanasy/name_afnet.cpp: In function ‘std::string af::msgMakeWriteHeader(const af::Msg*)’:
/workspace/build/cgru-master/afanasy/src/libafanasy/name_afnet.cpp:528: error: call of overloaded ‘to_string(int&)’ is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
/workspace/build/cgru-master/afanasy/src/libafanasy/name_afnet.cpp: In function ‘std::string af::getHttpHeader(int, const std::string&, const std::string&)’:
/workspace/build/cgru-master/afanasy/src/libafanasy/name_afnet.cpp:541: error: call of overloaded ‘to_string(int&)’ is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
/workspace/build/cgru-master/afanasy/src/libafanasy/name_afnet.cpp:543: error: call of overloaded ‘to_string(int&)’ is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
make[2]: *** [libafanasy/CMakeFiles/afanasy.dir/workspace/build/cgru-master/afanasy/src/libafanasy/name_afnet.cpp.o] Error 1
```

**Comment by timurhai** [comment]
Hi.
No.
May be that can be rewritten to avoid modern functions.

**Comment by lithorus** [comment]
The 'back' and 'pop_back' can be fixed by adding :
CXXFLAGS=-std=c++11
However it would perhaps be nice to have more of the c++11 features availible like to_string.
Can't gcc 4.8 (which should support it) be installed on Centos/RHEL6?
Also VFXplatform has had gcc-4.8.2 as a requirement since 2015...
[](http://vfxplatform.com)

**Comment by lithorus** [comment]
Using this :
https://gist.github.com/giwa/b1fb1e44dc0a7d270881
and
CXXFLAGS="-std=c++11 -lrt" in front of the build command builds it under Centos 6.9

**Comment by sebastianelsner** [comment]
Trying to compile on CentOS 6.6 gives me an unknown option error for c++11, i have to use c++0x and that one does not fix the problem

as for the gcc 4.8: I am under the impression you need a) a redhat subscription and b) internet on the workstation to activate/download the repo/rpms. I do have a) but we are completely offline on workstations in the office.

**Comment by timurhai** [comment]
Hi.
So, what is with this issue?

**Comment by sebastianelsner** [comment]
I think we can close it, compiling with 4.8 works. but native support for CentOS 6 is broken

**Comment by timurhai** [comment]
There just std::string::back() std::string::pop_back() and std::to_string() functions, that can be easily replaced (af::itos already exists).

So i think that we can keep CentOS 6 support for some time.

When we will use something really useful/smart from c++11 we will define that this standard is required for the project.

**Comment by timurhai** [comment]
Back from c++11 committed:
https://github.com/CGRU/cgru/commit/177bd26a3fa2d41646dbb50c54e6b2b0531be298

**Comment by timurhai** [comment]
Later we can use c++11, when we will take something smart from there, not just those small and unnecessary functions.
