### ISSUE TITLE
afermer requires atleast Qt 5.7

### ISSUE THREAD

**Issue by lithorus** [CGRU/cgru#329]
I'm getting these compile errors :

`/opt/cgru/afanasy/src/fermer/RotateValue.cpp: In member function 'bool afermer::RotateValue::addValue(int)':
/opt/cgru/afanasy/src/fermer/RotateValue.cpp:15:24: error: 'class QList<int>' has no member named 'rbegin'
     std::rotate(m_list.rbegin(),m_list.rbegin()+1,m_list.rend());
                        ^
/opt/cgru/afanasy/src/fermer/RotateValue.cpp:15:40: error: 'class QList<int>' has no member named 'rbegin'
     std::rotate(m_list.rbegin(),m_list.rbegin()+1,m_list.rend());
                                        ^
/opt/cgru/afanasy/src/fermer/RotateValue.cpp:15:58: error: 'class QList<int>' has no member named 'rend'
     std::rotate(m_list.rbegin(),m_list.rbegin()+1,m_list.rend());`

And according to http://doc.qt.io/qt-5/qlist.html#rbegin
rbegin() is supported from Qt 5.6 and onwards.

Also, some of the qml files requires QtQuick 2.7 which is the version in Qt 5.7

**Comment by timurhai** [comment]
I managed to build it only on Qt5.7.
It also needs QtQuick 2 to work.
Later we should make some check for it in cmake.

**Comment by lithorus** [comment]
Or make it work with 5.5? I don't think alot of distros ship with 5.7 yet.
Ubuntu 16.04 for instance is on 5.5. Or should we bundle with Qt libraries?

**Comment by sergiy-nazarenko** [comment]
Hi, It's true that afermer can be build only with Qt5.7 because there is many bugs in QML in the previous Qt versions. Unfortunately.
Do you use Rez-config? I can give you Rez package to build Qt-5.7 .

**Comment by RiLights** [comment]
Actually right now AFermer on the alfa testing and maybe it is so bad idea to leave him for experience users who can try and build Qt 5.7.
Time will show, whan we will release version with all planing features maybe than all major platform will support Qt 5.7 :)

**Comment by timurhai** [comment]
Qt Quick 2 available only since Qt-5.7.0.
It seems that this GUI is too modern, but it is not finished and tested enough.
May be later most modern distributions will have Qt-5.7.

**Comment by timurhai** [comment]
wow )
i wrote almost the same at same time !

**Comment by lithorus** [comment]
The fact that Ubuntu 16.04 is the latest stable until april 2018 it'll take some time for that to happen for Ubuntu. Centos is still on Qt 4.x according to distrowatch.

Perhaps maintaining our own distribution of Qt 5.7 wouldn't be a bad idea? Windows can use the MSVC compiled version which means no re-compiling there and for Linux we can re-compile from scratch. I think it will speed up the adoption/testing of afermer.

**Comment by lithorus** [comment]
Also Qt Quick 2.5 is in Qt 5.6. 
http://doc.qt.io/qt-5.6/qtquick-qmlmodule.html
And Qt 5.6.1 is VFX platform CY2017
http://www.vfxplatform.com/

**Comment by RiLights** [comment]
On first stage of testing AFermer we used Qt 5.6 but unfortunately QtQuick 2.5 has serious bugs (for example with context menu) that is why AFermer require at least QtQuick 2.7.

More and more studios have involved to rez-config system which will not have any trouble to interference with system libs and your own libraries. 

https://github.com/nerdvegas/rez

**Comment by lithorus** [comment]
OK, so Qt 5.7 makes sense. Also it seems that qt.io has downloads for pre-compiled versions which I think we are able to distribute even in binary packages. This would make it easier for everyone and an environment much better controlled (similar to what rez-config does) and easier to constantly update.
